// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        avatar: string
        jump: string
        pop: string
        pulse: string
        pulseVoted: string
        score: string
        tooltip: string
        voted: string
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
