// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        'align-baseline': string
        'align-center': string
        'align-end': string
        'align-start': string
        'align-stretch': string
        box: string
        column: string
        container: string
        fullHeight: string
        fullWidth: string
        'justify-around': string
        'justify-between': string
        'justify-center': string
        'justify-end': string
        'justify-evenly': string
        'justify-start': string
        row: string
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
